@echo off >nul 2>&1
chcp 949 >nul 2>&1
setlocal >nul 2>&1
cls

:: =============================================================================
:: LFS Tools Launcher v1.0
:: Auto-generated by LFS-Tools-Compiler
:: =============================================================================

cd /d "%~dp0" >nul 2>&1

if not exist "LFS-Tools" (
    echo [ERROR] LFS-Tools 디렉터리를 찾을 수 없습니다
    echo [TIP] LFS-Tools-Compiler.bat를 먼저 실행하세요.
    pause >nul
    exit /b 1
)

if not exist "LFS-Tools\Auto-LFS-Tracker.exe" (
    echo [ERROR] Auto-LFS-Tracker.exe를 찾을 수 없습니다
    pause >nul
    exit /b 1
)

if not exist "LFS-Tools\LFS-Migration.exe" (
    echo [ERROR] LFS-Migration.exe를 찾을 수 없습니다
    pause >nul
    exit /b 1
)

:menu
cls >nul 2>&1
echo ================================================================================
echo                            LFS Tools Launcher v1.0
echo ================================================================================
echo.
echo   [1] Auto-LFS-Tracker    - 대용량 파일 스캔 및 LFS 자동 설정
echo   [2] LFS-Migration       - 기존 파일을 LFS로 마이그레이션
echo   [3] 도구 정보 보기       - 컴파일된 도구 상태 확인
echo   [4] 종료                - 프로그램 종료
echo.
echo ================================================================================
echo.
choice /c 1234 /n /m "선택하세요 ^(1-4^): " >nul 2>&1
if errorlevel 4 goto :end
if errorlevel 3 goto :info  
if errorlevel 2 goto :migration
if errorlevel 1 goto :tracker
goto :menu

:tracker
cls >nul 2>&1
echo [EXECUTE] Auto-LFS-Tracker를 실행합니다...
echo ================================================================================
"LFS-Tools\Auto-LFS-Tracker.exe"
echo.
pause >nul
goto :menu

:migration
cls >nul 2>&1
echo [EXECUTE] LFS-Migration을 실행합니다...
echo ================================================================================
"LFS-Tools\LFS-Migration.exe"
echo.
pause >nul
goto :menu

:info
cls >nul 2>&1
echo ================================================================================
echo                              도구 정보
echo ================================================================================
echo.
dir "LFS-Tools\*.exe" /b 2>nul
echo.
pause >nul
goto :menu

:end
cls >nul 2>&1
echo [EXIT] LFS Tools Launcher를 종료합니다.
echo 감사합니다
exit /b 0
