@echo off >nul 2>&1
chcp 949 >nul 2>&1
setlocal >nul 2>&1
cls

:: =============================================================================
:: LFS Tools Launcher v1.0
:: Auto-generated by LFS-Tools-Compiler
:: =============================================================================

cd /d "%~dp0" >nul 2>&1

if not exist "LFS-Tools" (
    echo [ERROR] LFS-Tools 디렉터리를 찾을 수 없습니다
    echo [TIP] LFS-Tools-Compiler.bat를 먼저 실행하세요.
    pause >nul
    exit /b 1
)

if not exist "LFS-Tools\Auto-LFS-Tracker.exe" (
    echo [ERROR] Auto-LFS-Tracker.exe를 찾을 수 없습니다
    pause >nul
    exit /b 1
)

if not exist "LFS-Tools\LFS-Migration.exe" (
    echo [ERROR] LFS-Migration.exe를 찾을 수 없습니다
    pause >nul
    exit /b 1
)

:menu
cls >nul 2>&1
echo ================================================================================
echo                            LFS Tools Launcher v1.0
echo ================================================================================
echo.
echo   [1] Auto-LFS-Tracker    - 대용량 파일 스캔 및 LFS 자동 설정
echo   [2] LFS-Migration       - 기존 파일을 LFS로 마이그레이션
echo   [3] 도구 정보 보기       - 컴파일된 도구 상태 확인
echo   [4] 종료                - 프로그램 종료
echo.
echo ================================================================================
echo.
choice /c 1234 /n /m "선택하세요 ^(1-4^): " 2>nul
if errorlevel 4 goto :end
if errorlevel 3 goto :info  
if errorlevel 2 goto :migration
if errorlevel 1 goto :tracker
goto :menu

:tracker
cls >nul 2>&1
echo [AUTO] .gitignore 체크 및 LFS 도구 예외처리...
call :update_gitignore
echo [EXECUTE] Auto-LFS-Tracker를 실행합니다...
echo ================================================================================
"LFS-Tools\Auto-LFS-Tracker.exe"
echo.
pause >nul
goto :menu

:migration
cls >nul 2>&1
echo [AUTO] .gitignore 체크 및 LFS 도구 예외처리...
call :update_gitignore
echo [EXECUTE] LFS-Migration을 실행합니다...
echo ================================================================================
"LFS-Tools\LFS-Migration.exe"
echo.
pause >nul
goto :menu

:info
cls >nul 2>&1
echo ================================================================================
echo                              도구 정보
echo ================================================================================
echo.
dir "LFS-Tools\*.exe" /b 2>nul
echo.
pause >nul
goto :menu

:update_gitignore
if exist ".gitignore" (
    findstr /i "LFS-Tools" .gitignore >nul 2>&1
    if not errorlevel 1 (
        echo [SKIP] .gitignore에 이미 LFS 도구 예외처리가 있습니다.
        goto :eof
    )
)
echo [ADD] .gitignore에 LFS 도구 예외처리 추가 중...
(
echo.
echo # LFS Tools - Auto-generated
echo LFS-Tools/
echo LFS-launcher.bat
echo *.exe
) >> .gitignore 2>nul
if exist ".gitignore" (
    echo [SUCCESS] .gitignore 업데이트 완료
) else (
    echo [WARN] .gitignore 업데이트에 실패했습니다
)
goto :eof

:end
cls >nul 2>&1
echo [EXIT] LFS Tools Launcher를 종료합니다.
echo 감사합니다
exit /b 0
